apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/djbledgj-tenant/devfile-sample/devfile-sample@sha256:ee305643869e4f43a812065d8e7f5c4c9cd11e2f8400adb7e15fabbe183286a6
        name: my-nodejs
        resources: {}
status: {}
